### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by erikiveroth** [calmh/ipfixcat#2]
Got "index out of range", using supplied procera-fields.ini as dict, with build 0.2.6 (for linux amd64).
In the same environment, build 0.2.5 worked fine before the upgrade.

PCAP of traffic will be sent in a PM

```
"panic: runtime error: index out of range

goroutine 5 [running]:
github.com/calmh/ipfix.interpretBytes(0xc20800c446, 0x0, 0x8f, 0x2, 0x0, 0x0)
    /Users/jb/src/github.com/calmh/ipfix/interpreter.go:168 +0x275
github.com/calmh/ipfix.(*Interpreter).Interpret(0xc208032300, 0x92bc, 0xc208066000, 0x1b, 0x1b, 0x0, 0x0, 0x0)
    /Users/jb/src/github.com/calmh/ipfix/interpreter.go:118 +0x333
main.func·001()
    /Users/jb/src/github.com/calmh/ipfixcat/main.go:56 +0x350
created by main.messagesGenerator
    /Users/jb/src/github.com/calmh/ipfixcat/main.go:67 +0x1dc

goroutine 1 [runnable]:
main.main()
    /Users/jb/src/github.com/calmh/ipfixcat/main.go:106 +0xd3f
2015/05/20 20:11:07 socat[15017] E write(1, 0x1ba70c0, 1308): Broken pipe"
```

**Comment by calmh** [comment]
(https://github.com/calmh/ipfix/blob/26d054f2b23620afa63a3014e59f5f9988e0b455/interpreter.go#L168 looks like broken or misinterpreted data...)

**Comment by calmh** [comment]
Fixed a long while back I think. :)
